# Generated by Django 4.2.27 on 2026-01-20 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CravingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigarettes_smoked', models.PositiveIntegerField()),
                ('smoke_free_day', models.BooleanField()),
                ('first_cigarette_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('craving_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quit_smoking_webapp.cravinglevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationQuoteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigarettes_per_day', models.PositiveIntegerField()),
                ('pack_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason_to_quit', models.TextField()),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('quote_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.motivationquotetype')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.dailylog')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.situation')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.dailylog')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_chat_response', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
