# Generated by Django 4.2.27 on 2026-03-26 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quit_smoking_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogemotion',
            name='custom_emotion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dailylogsituation',
            name='custom_situation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailylogemotion',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.emotion'),
        ),
        migrations.AlterField(
            model_name='dailylogsituation',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quit_smoking_webapp.situation'),
        ),
    ]
