# Generated by Django 4.2.27 on 2026-04-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quit_smoking_webapp', '0002_dailylogemotion_custom_emotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reminder_enabled',
        ),
    ]
