# Generated by Django 4.2.27 on 2026-04-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quit_smoking_webapp', '0003_remove_userprofile_reminder_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ranking_consent',
            field=models.BooleanField(default=False),
        ),
    ]
